version: '3'
services:
  fountain:
    build: fountain
    ports: 
      - "5001:80"
  discovery:
    build: discovery
    environment:
      - QUERY_CACHE_HOST=redis
      - SPARQL_HOST=http://graph:7200/repositories/tds
      - REPOSITORY_BASE=http://agora.org/data/
      - UPDATE_HOST=http://graph:7200/repositories/tds/statements
      - EXTENSION_BASE=http://agora.org/extensions/
      - FOUNTAIN_HOST=fountain
      - FOUNTAIN_PORT=80
      - API_PORT=80
      - TERM=xterm
  graph:
    image: dhlabbasel/graphdb-free
    ports:
      - "7200:7200"
  nginx:
    build: nginx
    ports: 
      - "8000:80"
    environment:
      - TERM=xterm



