version: '3'
services:
  redis:
    image: redis
  fountain:
    build: fountain
    ports: 
      - "5000"
    environment:
      - FOUNTAIN_DB_HOST=redis
  discovery:
    build: discovery
#    ports:
#      - "8000:8000"
    environment:
      - QUERY_CACHE_HOST=redis
      - SPARQL_HOST=http://graph:7200/repositories/tds
      - REPOSITORY_BASE=http://vicinity.eu/data/
      - UPDATE_HOST=http://graph:7200/repositories/tds/statements
      - EXTENSION_BASE=http://vicinity.eu/extensions/
      - FOUNTAIN_HOST=fountain
      - FOUNTAIN_PORT=5000
      - API_PORT=8000
      - TERM=xterm
  graph:
    image: dhlabbasel/graphdb-free
    ports:
      - "7200:7200"
  nginx:
    build: nginx
    ports: 
      - "8000:80"
    environment:
      - TERM=xterm



